#!/bin/bash --login

# Usage:
#   gen_rails_app app_name path_to_parent_dir

# Assumptions:
#  - if parent directory isn't given, the project folder should be put in the
#    current directory
#  - the gemset should be named the same as the app, and should be created with
#    the current ruby version
#  - the script is being executed from the rails_template folder, which is where
#    the script is located (this assumption should be removed... just need to
#    make the path to the template an absolute path, and I think put the script
#    in /bin ... is there a better place to put the template and required
#    files?)

# Read input variables
app_name=$1
parent_dir=${2:-'./'}

# Create project folder and gemset
mkdir "${parent_dir}/${app_name}"
cd "${parent_dir}/${app_name}"
rvm gemset create $app_name
rvm gemset use $app_name
rvm --create --ruby-version $(rvm current) &> /dev/null

echo "Installing rails gem in new gemset"
# prevent rails install from failing while compiling nokogiri's binaries:
gem install nokogiri -- --use-system-libraries
gem install rails -v '~> 5.0.0'

echo "Creating the rails app"
rails new . -T -d=postgresql -m ~/Desktop/Code/rails_app_template/app_template.rb

echo "Running the specs"
bin/rspec
