#!/bin/bash --login

# Usage:
#   rm_rails_app app_name path_to_parent_dir

# Assumptions:
#  - if parent directory isn't given, the project folder is assumed to be in the
#    current directory
#  - the gemset is named the same as the app, and the project uses the current
#    ruby version
#  - the script is being executed from the rails_template folder, which is where
#    the script is located (this assumption should be removed... just need to
#    make the path to the template an absolute path, and I think put the script
#    in /bin ... ?)

# Read input variables, save current state
app_name=$1
parent_dir=${2:-'./'}
orig_gemset=$(rvm current)
orig_dir=$(pwd)

# Delete databases
cd "${parent_dir}/${app_name}"
rails db:drop || \
  echo -e "\x1B[31m\x1B[1mError:\x1B[21m Couldn't drop the databases... maybe they \
  were never created?\x1B[0m"

echo "Deleting source code..."
cd ../
rm -rf $app_name
cd $orig_dir

echo "Deleting gemset..."
if [[ "$orig_gemset" == *"$app_name" ]]; then
  rvm gemset use default
fi
rvm gemset delete $app_name
